import { motion } from "framer-motion";
import { BakedTextImageCard } from "@/components/public/BakedTextImageCard";
import { SectionContainer } from "@/components/public/SectionContainer";

const climateCards = [
  {
    title: "Scope 3 supply chain engagement",
    imageUrl: "/engage.webp",
    imageAlt: "Scope 3 supply chain engagement",
  },
  {
    title: "Regenerative agriculture initiatives",
    imageUrl: "/agri.webp",
    imageAlt: "Regenerative agriculture initiatives",
  },
  {
    title: "Sustainable sourcing frameworks",
    imageUrl: "/sustainable.webp",
    imageAlt: "Sustainable sourcing frameworks",
  },
];

const impactItems = [
  "Improved household income from coffee",
  "Renewable energy access",
  "Reduced pressure on forests",
  "Improved soil fertility",
  "Expanded roles for women in coffee communities",
];

export const ImpactSection = () => {
  return (
    <section id="impact" className="bg-background py-24 md:py-28">
      <SectionContainer size="wide" className="space-y-12">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8 }}
          className="bloom-panel p-6 md:p-8"
        >
          <p className="text-xs font-semibold uppercase tracking-[0.16em] text-bloomGold">CLIMATE &amp; SUPPLY CHAIN ALIGNMENT</p>
          <h2 className="mt-3 text-4xl leading-tight text-bloomDarkCoffee md:text-5xl">Supporting Sustainable Coffee Systems</h2>

          <div className="mt-6 space-y-5 text-base leading-relaxed text-bloomDarkCoffee/80 md:text-lg">
            <p>
              The outcomes generated by the 3rd Harvest initiative contribute to broader sustainability priorities within the coffee sector.
            </p>
            <p>
              By converting organic coffee waste into renewable energy and reducing dependence on firewood, the system helps reduce emissions and pressure on forests.
            </p>
            <p>
              At the same time, soil regeneration and renewable energy access strengthen farm resilience and long-term productivity.
            </p>
            <p>
              For coffee companies and industry partners, participation in the initiative can support climate and sustainability strategies including:
            </p>
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8, delay: 0.05 }}
          className="grid gap-5 md:grid-cols-3"
          data-testid="climate-cards-grid"
        >
          {climateCards.map((card) => (
            <BakedTextImageCard key={card.title} imageUrl={card.imageUrl} imageAlt={card.imageAlt} title={card.title} className="min-h-[280px]" />
          ))}
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8, delay: 0.1 }}
          className="bloom-panel p-6 md:p-8"
        >
          <p className="text-xs font-semibold uppercase tracking-[0.16em] text-bloomGold">IMPACT</p>
          <h2 className="mt-3 text-4xl leading-tight text-bloomDarkCoffee md:text-5xl">Transforming the First Mile of Coffee</h2>

          <p className="mt-6 text-base leading-relaxed text-bloomDarkCoffee/80 md:text-lg">
            3rd Harvest generates measurable outcomes across multiple dimensions.
          </p>
          <p className="mt-4 text-base leading-relaxed text-bloomDarkCoffee/80 md:text-lg">Impact areas include:</p>

          <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3" data-testid="impact-cards-grid">
            {impactItems.map((item) => (
              <article
                key={item}
                className="rounded-xl border border-black/10 bg-bloomBeige/80 px-5 py-5 text-sm font-semibold tracking-[0.01em] text-bloomDarkCoffee md:text-base"
              >
                • {item}
              </article>
            ))}
          </div>

          <p className="mt-6 text-base leading-relaxed text-bloomDarkCoffee/80 md:text-lg">
            Impact metrics are tracked through the 3rd Harvest Impact Framework, supporting partner ESG and sustainability reporting.
          </p>
        </motion.div>
      </SectionContainer>
    </section>
  );
};
